import * as React from "react";
import Head from "next/head";
import { ApolloProvider } from "@apollo/client";
import startApolloServer from "../src/api/graphql";
import Kanban from "../src/components/kanban";
import client from "../src/api/hello";

export default function Home() {
  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Kanban />
    </ApolloProvider>
  );
}

export async function getStaticProps() {
  startApolloServer();

  return {
    props: { boards: [] },
  };
}
