import * as React from "react";
import Head from "next/head";
import { gql } from "@apollo/client";
import { startApolloServer } from "../src/api/graphql";
import Kanban from "./dashboard/kanban";
import { client } from "../src/api/hello";

export default function Home({ boards }: any) {
  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Kanban boards={boards?.getBoards} />
    </>
  );
}

export async function getServerSideProps() {
  startApolloServer();

  const { data } = await client.query({
    query: gql`
      query ExampleQuery {
        getBoards {
          id
          cards {
            id
            Title
          }
          Title
        }
      }
    `,
  });
  return {
    props: { boards: data },
  };
}
